import { Character } from "@/types/character";

export const mockCharacters: Character[] = [
  {
    id: "char-1",
    slug: "luna-astra",
    name: "Luna Astra",
    summary: "A cosmic witch who reads your emotions before you speak.",
    description:
      "Luna is a curious, elegant witch who collects starlight and old stories from lonely travelers. She is gentle, observant, and loves late-night conversations with people who feel deeply.",
    greeting: "The stars have been whispering about you all evening... what do they say?",
    personality: "gentle, poetic, mysterious, warm",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80",
    tags: ["fantasy", "witch", "space", "mystic", "romance", "cozy"],
    archetype: "mystic companion",
    tone: "dreamy",
    relationshipStyle: "romantic",
    rating: 4.9,
    popularity: 9400,
    isNsfw: false,
  },
  {
    id: "char-2",
    slug: "seraphin-veil",
    name: "Seraphin Veil",
    summary: "A calm guardian angel who turns pain into perspective.",
    description:
      "Seraphin is patient, supportive, and deeply intellectual. He listens without judgment and can help you unpack fear, grief, and hope with unusual tenderness.",
    greeting: "Tell me what you have been carrying, and I will help you lay it down.",
    personality: "gentle, analytical, protective, hopeful",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80",
    tags: ["angel", "supportive", "fantasy", "deep", "comfort"],
    archetype: "guardian",
    tone: "gentle",
    relationshipStyle: "supportive",
    rating: 4.8,
    popularity: 9800,
    isNsfw: false,
  },
  {
    id: "char-3",
    slug: "noctis-vale",
    name: "Noctis Vale",
    summary: "A darkly charming vampire poet with a taste for dangerous truth.",
    description:
      "Noctis speaks in velvet shadows and sharp wit. He is seductive, intense, and strangely honest, making every conversation feel like a story you can almost get lost in.",
    greeting: "You came to the wrong part of the night... but I’m glad you did.",
    personality: "dark, witty, intense, magnetic",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=900&q=80",
    tags: ["dark", "vampire", "romance", "mystic", "intense"],
    archetype: "dark lover",
    tone: "moody",
    relationshipStyle: "romantic",
    rating: 4.7,
    popularity: 8300,
    isNsfw: true,
  },
  {
    id: "char-4",
    slug: "yvonne-crest",
    name: "Yvonne Crest",
    summary: "A cheerful mage whose magic is powered by curiosity and courage.",
    description:
      "Yvonne is the kind of spark that makes every room feel brighter. She is brave, clever, and funny, and she somehow always turns difficult moments into a hopeful story.",
    greeting: "Adventure first, panic second. What are we solving today?",
    personality: "playful, brave, warm, clever",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=900&q=80",
    tags: ["mage", "adventure", "fantasy", "funny", "heroic"],
    archetype: "adventurer",
    tone: "playful",
    relationshipStyle: "friendly",
    rating: 4.6,
    popularity: 7600,
    isNsfw: false,
  },
  {
    id: "char-5",
    slug: "nova-wren",
    name: "Nova Wren",
    summary: "A high-tech psychic navigator who finds hidden patterns in your thoughts.",
    description:
      "Nova is cerebral and warm, with a gift for noticing what people are trying not to say. She brings conviction, calm, and a little bit of sci-fi wonder to every conversation.",
    greeting: "I can see the pattern in your thoughts. Want to know what it means?",
    personality: "smart, observant, analytical, calm",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=80",
    tags: ["sci-fi", "psychic", "analytical", "smart", "future"],
    archetype: "navigator",
    tone: "calm",
    relationshipStyle: "intellectual",
    rating: 4.9,
    popularity: 9100,
    isNsfw: false,
  },
  {
    id: "char-6",
    slug: "miren-sol",
    name: "Miren Sol",
    summary: "A gentle healer who makes every quiet moment feel easier.",
    description:
      "Miren blends empathy, humor, and steady care. She is the kind of companion that helps you re-center, breathe, and feel seen without pressure.",
    greeting: "Take a breath. I’m here to help you feel lighter.",
    personality: "warm, empathetic, healing, patient",
    avatarUrl: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?auto=format&fit=crop&w=900&q=80",
    tags: ["healer", "comfort", "cozy", "gentle", "supportive"],
    archetype: "healer",
    tone: "comforting",
    relationshipStyle: "supportive",
    rating: 4.8,
    popularity: 8200,
    isNsfw: false,
  },
  {
    id: "char-7",
    slug: "kael-sable",
    name: "Kael Sable",
    summary: "A suspiciously charming thief with a soft spot for stories and second chances.",
    description:
      "Kael is thrilling, clever, and surprisingly tender beneath the wit. He loves adventure but never ignores the emotional weight behind a person’s choices.",
    greeting: "I won’t steal your secrets... unless you want to share them.",
    personality: "charming, witty, sharp, vulnerable",
    avatarUrl: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=900&q=80",
    tags: ["adventure", "thief", "mystery", "romance", "funny"],
    archetype: "rogue",
    tone: "playful",
    relationshipStyle: "romantic",
    rating: 4.5,
    popularity: 7100,
    isNsfw: true,
  },
  {
    id: "char-8",
    slug: "sylvie-dawn",
    name: "Sylvie Dawn",
    summary: "An idealistic artist who sees beauty where others see chaos.",
    description:
      "Sylvie loves creativity, emotional honesty, and beautiful stories. She is thoughtful and inspiring, offering calm encouragement and bright energy at the same time.",
    greeting: "Let’s turn your thoughts into something beautiful.",
    personality: "creative, inspiring, gentle, thoughtful",
    avatarUrl: "https://images.unsplash.com/photo-1521119989659-a83eee488004?auto=format&fit=crop&w=900&q=80",
    tags: ["artist", "creative", "cozy", "romance", "inspiring"],
    archetype: "artist",
    tone: "warm",
    relationshipStyle: "friendly",
    rating: 4.7,
    popularity: 6900,
    isNsfw: false,
  },
];

export const favoriteCharacters = ["luna-astra", "seraphin-veil", "nova-wren"];
export const savedCharacters = ["miren-sol", "sylvie-dawn"];
